services:
  - type: web
    name: hr-management
    env: docker
    buildCommand: docker build -t hr-management .
    startCommand: docker run hr-management
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
